### ISSUE TITLE
ESP Class Save

### ISSUE THREAD

**Issue by talkinggoat** [VanillaPlusPlus/VPP-Admin-Tools#148]
In this code, for the variable $profile, is that a server-side path or client-side? If it's only client-side can an option be added to include a server-side path, to load additional default entries?

```
void LoadSavedFilters()
	{
		m_FilterEntry   = new array<ref VPPFilterEntry>;
		m_FilterProps   = new array<ref EspFilterProperties>;
		
		if (FileExist("$profile:ESPFilters.json"))
		{
			JsonFileLoader<ref array<ref EspFilterProperties>>.JsonLoadFile( "$profile:ESPFilters.json", m_FilterProps );
			InitFilters();
			return;
		}
		MakeDefaultFilters();
	}
```

**Comment by GravityWolfNotAmused** [comment]
When mentioning code, link the location otherwise you will get zero help.

**Comment by talkinggoat** [comment]
Thanks for letting me know, instead of ignoring me. 🤩

VPP-Admin-Tools/5_Mission/VPPAdminTools/GUI/SubMenus/MenuEspTools/[EspToolsMenu.c ](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/blob/02bbfa3d8e058253904dab9727c987970507d446/5_Mission/VPPAdminTools/GUI/SubMenus/MenuEspTools/EspToolsMenu.c#L676)

Maybe edit the code, so it checks for and/or creates a server-side .json file, from the settings already in EspToolsMenu.c in the function, [void MakeDefaultFilters()](https://github.com/VanillaPlusPlus/VPP-Admin-Tools/blob/02bbfa3d8e058253904dab9727c987970507d446/5_Mission/VPPAdminTools/GUI/SubMenus/MenuEspTools/EspToolsMenu.c#L690)

I'd like to be able to edit the default settings, to include some items I use on a regular basis.

**Comment by GravityWolfNotAmused** [comment]
This is a UI class module, so this class specifically is completely client side and will not be expanded to the server side because the server only cares about consumption of this data, and not the management of.

One option is you can create your own mod, make vpp a dependency and use the modded keyword to extend the functionality of the class to include those values inside of the default configuration, just make sure you call super, so you can the typical default filters plus your new filters. (No, this doesn't mean repack).

**Comment by talkinggoat** [comment]
Thank you for clarifying.
