### ISSUE TITLE
SERVER CRASH

### ISSUE THREAD

**Issue by uDAREGriev** [VanillaPlusPlus/VPP-Admin-Tools#4]
Had to remove V++ and i want it back its very cool the below error consistantly crashes the server over a 24h period serveral crashes with this always the last crash entry, removed V++ server back stable.

WIN-MDRS7HD5EKU, 06.04 2019 23:41:34

A particle was spawned on server-side! Particles can be spawned on client-side only!
Class:      'Land_Wreck_C130J'
Entity id:-9221779943454545350

Function: 'Error'
Stack trace:
scripts/1_Core/proto\endebug.c:44
scripts/3_Game/particle.c:451
scripts/3_Game/particle.c:419
scripts/3_Game/particle.c:481
VanillaPP/scripts/4_World/entities\building\wrecks\land_wreck_c130j.c:22

**Comment by Ondra97** [comment]
yea.. some little fixie for this crash would be nice^^

**Comment by LaGTeK** [comment]
Disable airdrop can't fix this ?

**Comment by GravityWolfNotAmused** [comment]
> Disable airdrop can't fix this ?

Should be able to, I am going to look over all bugs tonight, and plan for updates.

**Comment by uDAREGriev** [comment]
Nope they are set to false.. i did try them for a while but that gave a different error so i switched them off in the config

**Comment by GravityWolfNotAmused** [comment]
We might delete a bunch of things, like the supply drops, from the mod. We have been discussing if we wanted to keep the project whole, or break it into parts for people to pick and choose, so for instance, VPP will lose built in map since it's already available as a standalone mod, this will allow for easier updates, and quicker patches, while allowing for bugs to be specific to their workshop content. So I believe, and he can always correct me if I am wrong, that I am beginning the refactor process on VPP, and section of the admin tools from the rest of the content. This will allow those who just need an Admin tool solution, which is the majority of our user base, to have their fix sooner than later. 

For those who are concerned. if we cut a feature out of the stable VPP repository, please contact me, and I will try to make haste turning that feature into a standalone mod.

You know, I worked on VPP toward the beginning before I knew a quarter of what I know now, and I believe that refactor will be a lot faster than the previous refactor. I've been so grateful for all the support from the community, and your feedback means so much to me, just please understand that I have many projects, and that currently this is the only thing paying my bills, so please, bare with me, and I will get started tonight.

**Comment by uDAREGriev** [comment]
awesome buddy. If one of the core mods could just be the spawn selection manager and admin tool that would be sweet

**Comment by GravityWolfNotAmused** [comment]
I am actually wanting to make the spawn menu a separate mod, keeping it integrated with VPP makes things harder on us, I will see what I can do.

**Comment by GravityWolfNotAmused** [comment]
Updated to: https://github.com/VanillaPlusPlus/VPP-Admin-Tools/commit/8c0fe7912c6007d5bc937397a78e0e45ef8ccffa

Please try the admin tools, and please report any new issues to this github repository, thank you for your time. I hope it was quick enough.
