### ISSUE TITLE
Esc button resets VPP Tools

### ISSUE THREAD

**Issue by T4nk22** [VanillaPlusPlus/VPP-Admin-Tools#54]
When I press the esc button my tool windows in VPP Admin Tools all close. When truning on esp then pressing esc it turns off esp and resets all windows. This just started happening a few days ago. I have another server that works fine. I also uninstalled the mod and removed the server folder and reinstalled and it still is happening.

**Comment by GravityWolfNotAmused** [comment]
This is intentional in our design as the Escape key is our close button for the tools, and the menus. If you wish to hide the menu, press the same key you use to open the menu, but understand the menu's themselves control the trackers in the ESP menu, so not having the menu open will stop new entries from being added, or old ones to be removed.
